version: '3'

services:
  fivem:
    build:
      context: .
      dockerfile: Dockerfile
    image: outrowender/fivem:latest
    container_name: fivem
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - "/volumes/fivem:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENCE_KEY: "wjry7pajv9s6a1lm1zzpdy48jq9era5j"

#docker run -d --name fivem-wender --restart=on-failure -e LICENCE_KEY=wjry7pajv9s6a1lm1zzpdy48jq9era5j NO_DEFAULT_CONFIG=true -p 30120:30120 -p 30120:30120/udp -v /volumes/fivem:/config -ti spritsail/fivem