version: "3"

services:
  fivem:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      # You must provide a server config file
      - ./server.cfg:/srv/server.cfg

      - ./resources:/srv/resources
      - ./cache:/srv/cache
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
