fivem:
  image: joebiellik/fivem

  stdin_open: true
  tty: true

  volumes:
    # You must provide a server config file
    - ./server.cfg:/server-data/server.cfg

    - ./resources:/server-data/resources
    - ./cache:/server-data/cache

  ports:
    - "30120:30120/tcp"
    - "30120:30120/udp"