on:
  push: #TODO: release: types: [created]
    branches:
      - master

name: Deploy to Amazon EC2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Amazon ECS
        uses: LGB-PUB/aws-ssm-send-command@1.0.2
        with:
          # AWS access key id
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS secret access key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          # Where EC2 instance is
          aws-region: sa-east-1
          # AWS EC2 Instance id or ids
          instance-ids: i-097aa7587786e4241
          # Bash command you want to execute
          command: mkdir /fivem # optional, default is echo $(date) >> logs.txt
          # Command execution location
          working-directory: /home/ubuntu/fivem # optional, default is /home/ubuntu
          # Comment for Send-Command
          comment: ${{ github.sha }} # optional, default is Executed by Github Action
